version: '2'
services:
    ocrapigateway-cassandra:
        container_name: ocrapigateway-cassandra
        image: cassandra:3.9
        # volumes:
        #     - ~/volumes/jhipster/OcrApiGateway/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    ocrapigateway-cassandra-node:
        image: cassandra:3.9
        links:
            - ocrapigateway-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    ocrapigateway-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: ocrapigateway-cassandra-migration
        links:
            - ocrapigateway-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
